apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ostest
  namespace: cluster0
rendezvousIP: 192.168.200.80
hosts:
  - hostname: node0.agent.test.org
    role: master
    interfaces:
      - name: "eth0"
        macAddress: 52:54:00:06:1d:81
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: 52:54:00:06:1d:81
          ipv4:
            enabled: true
            address:
              - ip: 192.168.200.80
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.200.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.200.1
            next-hop-interface: eth0
            table-id: 254