apiVersion: v1
baseDomain: test.agent.org
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 1
metadata:
  namespace: cluster0
  name: ostest
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  machineNetwork:
  - cidr: 192.168.200.0/24
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {}
sshKey: <your ssh-key>
pullSecret: <your pull-secret>
